server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称,单机 hostname: localhost
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    service-url:
          # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
          # 单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
          # 相互注册
          #defaultZone: http://eureka7002.com:7002/eureka/
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #server:
        # 禁用自我保护,保证不可用服务被及时删除
        #enable-self-preservation: false
        #eviction-interval-timer-in-ms: 2000


